core_override_preset: easy_booking_pager
url_querystring:
  core_override: false
  querystring_key: pg
  index_base: 0
  encode_method: none
_core:
  default_config_hash: mOI48r0jAAs54q55bxRFCn8g6j-QsXsLFLheI6x7sSk
