<?php

/**
 * @file
 */

use Drupal\Core\Render\BubbleableMetadata;

/**
 * Implements hook_theme().
 */
function easy_booking_map_theme($existing, $type, $theme, $path) {
  return [
    'mapbox' => [
      'template' => 'mapbox',
      'variables' => [],
    ],
  ];
}

/**
 * Implements hook_token_info().
 */
function easy_booking_map_token_info() {
  $info['types'] = [
    'mapbox' => [
      'name' => t('Mapbox'),
      'description' => t('Global Mapbox tokens.'),
    ],
  ];

  $info['tokens'] = [
    'mapbox' => [
      'map' => [
        'name' => t('Map'),
        'description' => t('Mapbox map.'),
      ],
    ],
  ];

  return $info;
}

/**
 * Implements hook_tokens().
 */
function easy_booking_map_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];
  if ($type == 'mapbox') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'map':
          /** @var \Drupal\Core\Block\BlockManager $block_manager */
          $block_manager = \Drupal::service('plugin.manager.block');
          /** @var \Drupal\Core\Render\Renderer $renderer */
          $renderer = \Drupal::service('renderer');
          $plugin_block = $block_manager->createInstance('mapbox_block', []);
          $block = $plugin_block->build();
          $replacements[$original] = $renderer->render($block);
          break;
      }
    }
  }

  return $replacements;
}

/**
 * Implemented hook_page_attachments().
 */
function easy_booking_map_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'easy_booking_map/mapbox';
}
